<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Office;
use Carbon\Carbon;

class OfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $offices = [
            // NCR (National Capital Region)
            ['name' => 'Centr', 'has_hostel' => false],
            ['name' => 'NCR', 'has_hostel' => false],
            ['name' => 'MEO North', 'has_hostel' => false],
            ['name' => 'MEO East', 'has_hostel' => false],
            ['name' => 'MEO West', 'has_hostel' => false],
            ['name' => 'MEO South', 'has_hostel' => false],

            // CAR (Cordillera Administrative Region)
            ['name' => 'CAR', 'has_hostel' => false],
            ['name' => 'PENRO Abra', 'has_hostel' => false],
            ['name' => 'CENRO Bangued', 'has_hostel' => false],
            ['name' => 'CENRO Lagangilang', 'has_hostel' => false],
            ['name' => 'PENRO Apayao', 'has_hostel' => false],
            ['name' => 'CENRO Calanasan', 'has_hostel' => false],
            ['name' => 'CENRO Conner', 'has_hostel' => false],
            ['name' => 'PENRO Benguet', 'has_hostel' => false],
            ['name' => 'CENRO Baguio', 'has_hostel' => false],
            ['name' => 'CENRO Baguias', 'has_hostel' => false],
            ['name' => 'PENRO Ifugao', 'has_hostel' => false],
            ['name' => 'CENRO Alfonso Lista', 'has_hostel' => false],
            ['name' => 'CENRO Lamut', 'has_hostel' => false],
            ['name' => 'PENRO Kalinga', 'has_hostel' => false],
            ['name' => 'CENRO Pinukpuk', 'has_hostel' => false],
            ['name' => 'CENRO Tabuk', 'has_hostel' => false],
            ['name' => 'PENRO Mt. Province', 'has_hostel' => false],
            ['name' => 'CENRO Paracelis', 'has_hostel' => false],
            ['name' => 'CENRO Sabangan', 'has_hostel' => false],

            // Region 1
            ['name' => 'Region 1', 'has_hostel' => false],
            ['name' => 'PENRO Ilocos Norte', 'has_hostel' => false],
            ['name' => 'CENRO Laoag', 'has_hostel' => false],
            ['name' => 'CENRO Bangui', 'has_hostel' => false],
            ['name' => 'PENRO Ilocos Sur', 'has_hostel' => false],
            ['name' => 'CENRO Bantay', 'has_hostel' => false],
            ['name' => 'CENRO Tagudin', 'has_hostel' => false],
            ['name' => 'PENRO La Union', 'has_hostel' => false],
            ['name' => 'PENRO Pangasinan', 'has_hostel' => false],
            ['name' => 'CENRO Dagupan', 'has_hostel' => false],
            ['name' => 'CENRO Urdaneta', 'has_hostel' => false],
            ['name' => 'CENRO Alaminos', 'has_hostel' => false],

            // Region 2
            ['name' => 'Region 2', 'has_hostel' => false],
            ['name' => 'PENRO Batanes', 'has_hostel' => false],
            ['name' => 'PENRO Cagayan', 'has_hostel' => false],
            ['name' => 'CENRO Alcala', 'has_hostel' => false],
            ['name' => 'CENRO Solana', 'has_hostel' => false],
            ['name' => 'CENRO Aparri', 'has_hostel' => false],
            ['name' => 'CENRO Sanchez Mira', 'has_hostel' => false],
            ['name' => 'PENRO Isabela', 'has_hostel' => false],
            ['name' => 'CENRO Cabagan', 'has_hostel' => false],
            ['name' => 'CENRO Palanan', 'has_hostel' => false],
            ['name' => 'CENRO Cauayan', 'has_hostel' => false],
            ['name' => 'CENRO Naguilian', 'has_hostel' => false],
            ['name' => 'CENRO San Isidro', 'has_hostel' => false],
            ['name' => 'PENRO Nueva Vizcaya', 'has_hostel' => false],
            ['name' => 'CENRO Aritao', 'has_hostel' => false],
            ['name' => 'CENRO Dupax', 'has_hostel' => false],
            ['name' => 'PENRO Quirino', 'has_hostel' => false],
            ['name' => 'CENRO Diffun', 'has_hostel' => false],
            ['name' => 'CENRO Nagtipunan', 'has_hostel' => false],

            // Region 3
            ['name' => 'Region 3', 'has_hostel' => false],
            ['name' => 'PENRO Aurora', 'has_hostel' => false],
            ['name' => 'CENRO Casiguran', 'has_hostel' => false],
            ['name' => 'CENRO Dingalan', 'has_hostel' => false],
            ['name' => 'PENRO Bataan', 'has_hostel' => false],
            ['name' => 'CENRO Bagac', 'has_hostel' => false],
            ['name' => 'CENRO Dinalupihan', 'has_hostel' => false],
            ['name' => 'PENRO Bulacan', 'has_hostel' => false],
            ['name' => 'CENRO Baliuag', 'has_hostel' => false],
            ['name' => 'CENRO Guiguinto', 'has_hostel' => false],
            ['name' => 'PENRO Nueva Ecija', 'has_hostel' => false],
            ['name' => 'CENRO Cabanatuan City', 'has_hostel' => false],
            ['name' => 'CENRO Muñoz', 'has_hostel' => false],
            ['name' => 'PENRO Pampanga', 'has_hostel' => false],
            ['name' => 'PENRO Tarcal', 'has_hostel' => false],
            ['name' => 'CENRO Camiling', 'has_hostel' => false],
            ['name' => 'CENRO Capas', 'has_hostel' => false],
            ['name' => 'PENRO Zamales', 'has_hostel' => false],
            ['name' => 'CENRO Masinloc', 'has_hostel' => false],
            ['name' => 'CENRO Olangapo City', 'has_hostel' => false],

            // region 4a
            ['name' => 'CALABARZON', 'has_hostel' => false],
            ['name' => 'PENRO Cavite', 'has_hostel' => false],
            ['name' => 'PENRO Laguna', 'has_hostel' => false],
            ['name' => 'CENRO Sta. Cruz', 'has_hostel' => false],
            ['name' => 'PENRO Batangas', 'has_hostel' => false],
            ['name' => 'CENRO Lipa City', 'has_hostel' => false],
            ['name' => 'CENRO Calaca', 'has_hostel' => false],
            ['name' => 'PENRO Rizal', 'has_hostel' => false],
            ['name' => 'PENRO Quezon', 'has_hostel' => false],
            ['name' => 'CENRO Calauag', 'has_hostel' => false],
            ['name' => 'CENRO Catanauan', 'has_hostel' => false],
            ['name' => 'CENRO Tayabas', 'has_hostel' => false],
            ['name' => 'CENRO Real', 'has_hostel' => false],

            // region 4b
            ['name' => 'MIMAROPA', 'has_hostel' => false],
            ['name' => 'PENRO Occidental Mindoro', 'has_hostel' => false],
            ['name' => 'CENRO Sablayan', 'has_hostel' => false],
            ['name' => 'CENRO San Jose', 'has_hostel' => false],
            ['name' => 'PENRO Oriental Mindoro', 'has_hostel' => false],
            ['name' => 'CENRO Roxas', 'has_hostel' => false],
            ['name' => 'PENRO Marinduque', 'has_hostel' => false],
            ['name' => 'PENRO Palawan', 'has_hostel' => false],
            ['name' => 'CENRO Brooke\'s Point', 'has_hostel' => false],
            ['name' => 'CENRO Coron', 'has_hostel' => false],
            ['name' => 'CENRO Puerto Princesa', 'has_hostel' => false],
            ['name' => 'CENRO Quezon', 'has_hostel' => false],
            ['name' => 'CENRO Roxas', 'has_hostel' => false],
            ['name' => 'CENRO Taytay', 'has_hostel' => false],

            // Region 5
            ['name' => 'Region 5', 'has_hostel' => false],
            ['name' => 'PENRO Albay', 'has_hostel' => false],
            ['name' => 'CENRO Guinobatan', 'has_hostel' => false],
            ['name' => 'PENRO Camarines Norte', 'has_hostel' => false],
            ['name' => 'PENRO Camarines Sur', 'has_hostel' => false],
            ['name' => 'CENRO Iriga City', 'has_hostel' => false],
            ['name' => 'CENRO Goa', 'has_hostel' => false],
            ['name' => 'CENRO Sipocot', 'has_hostel' => false],
            ['name' => 'CENRO Mobo', 'has_hostel' => false],
            ['name' => 'CENRO San Jacinto', 'has_hostel' => false],
            ['name' => 'PENRO Catanduanes', 'has_hostel' => false],
            ['name' => 'PENRO Masbate', 'has_hostel' => false],
            ['name' => 'PENRO Sorsogon', 'has_hostel' => false],

            // Region 6
            ['name' => 'Region 6', 'has_hostel' => false],
            ['name' => 'PENRO Aklan', 'has_hostel' => false],
            ['name' => 'CENRO Boracay', 'has_hostel' => false],
            ['name' => 'PENRO Ilo-Ilo', 'has_hostel' => false],
            ['name' => 'CENRO Guimbal', 'has_hostel' => false],
            ['name' => 'CENRO Barotac Nuevo', 'has_hostel' => false],
            ['name' => 'CENRO Sara', 'has_hostel' => false],
            ['name' => 'PENRO Antique', 'has_hostel' => false],
            ['name' => 'CENRO Belision', 'has_hostel' => false],
            ['name' => 'CENRO Culasi', 'has_hostel' => false],
            ['name' => 'PENRO Guimaras', 'has_hostel' => false],
            ['name' => 'PENRO Negros Occidental', 'has_hostel' => false],
            ['name' => 'CENRO Bago City', 'has_hostel' => false],
            ['name' => 'CENRO Cadiz City', 'has_hostel' => false],
            ['name' => 'CENRO Kabankalan City', 'has_hostel' => false],
            ['name' => 'PENRO Capiz', 'has_hostel' => false],
            ['name' => 'CENRO Mambusao', 'has_hostel' => false],

            // Region 7
            ['name' => 'Region 7', 'has_hostel' => false],
            ['name' => 'PENRO Cebu', 'has_hostel' => false],
            ['name' => 'CENRO Cebu City', 'has_hostel' => false],
            ['name' => 'CENRO Argao', 'has_hostel' => false],
            ['name' => 'PENRO Bohol', 'has_hostel' => false],
            ['name' => 'CENRO Tagbilaran City', 'has_hostel' => false],
            ['name' => 'CENRO Talibon', 'has_hostel' => false],
            ['name' => 'PENRO Negros Oriental', 'has_hostel' => false],
            ['name' => 'CENRO Dumaguete City', 'has_hostel' => false],
            ['name' => 'CENRO Ayungon', 'has_hostel' => false],
            ['name' => 'CENRO Siquijor', 'has_hostel' => false],

            // Region 8
            ['name' => 'Region 8', 'has_hostel' => false],
            ['name' => 'PENRO Leyte', 'has_hostel' => false],
            ['name' => 'CENRO Palo', 'has_hostel' => false],
            ['name' => 'CENRO Baybay', 'has_hostel' => false],
            ['name' => 'CENRO Ormoc', 'has_hostel' => false],
            ['name' => 'PENRO Southern Leyte', 'has_hostel' => false],
            ['name' => 'CENRO Maasin', 'has_hostel' => false],
            ['name' => 'CENRO San Juan', 'has_hostel' => false],
            ['name' => 'PENRO Samar', 'has_hostel' => false],
            ['name' => 'CENRO Centro Catbalogan', 'has_hostel' => false],
            ['name' => 'CENRO Sta. Rita', 'has_hostel' => false],
            ['name' => 'PENRO Eastern Samar', 'has_hostel' => false],
            ['name' => 'CENRO Borongan', 'has_hostel' => false],
            ['name' => 'CENRO Dolores', 'has_hostel' => false],
            ['name' => 'PENRO Northern Samar', 'has_hostel' => false],
            ['name' => 'CENRO Catarman', 'has_hostel' => false],
            ['name' => 'CENRO Pambujan', 'has_hostel' => false],
            ['name' => 'PENRO Biliran', 'has_hostel' => false],

            // Region 9
            ['name' => 'Region 9', 'has_hostel' => false],
            ['name' => 'PENRO Zamboanga del Sur', 'has_hostel' => false],
            ['name' => 'CENRO Guipos', 'has_hostel' => false],
            ['name' => 'CENRO Ramon Magsaysay', 'has_hostel' => false],
            ['name' => 'PENRO Zamboanga del Norte', 'has_hostel' => false],
            ['name' => 'CENRO Piñan', 'has_hostel' => false],
            ['name' => 'CENRO Liloy', 'has_hostel' => false],
            ['name' => 'CENRO Manukan', 'has_hostel' => false],
            ['name' => 'CENRO Siocon', 'has_hostel' => false],
            ['name' => 'PENRO Zamboanga Sibugay', 'has_hostel' => false],
            ['name' => 'CENRO Imelda', 'has_hostel' => false],
            ['name' => 'CENRO Kabasalan', 'has_hostel' => false],
            ['name' => 'CENRO Zamboanga City', 'has_hostel' => false],

            // Region 10
            ['name' => 'Region 10', 'hostel_name' => 'Region 10 Hostel', 'has_hostel' => true],
            ['name' => 'PENRO Bukidnon', 'has_hostel' => false],
            ['name' => 'CENRO Manolo Fortich', 'has_hostel' => false],
            ['name' => 'CENRO Valencia', 'has_hostel' => false],
            ['name' => 'CENRO Don Carlos', 'has_hostel' => false],
            ['name' => 'CENRO Talakag', 'has_hostel' => false],
            ['name' => 'PENRO Misamis Occidental', 'has_hostel' => false],
            ['name' => 'CENRO Ozamis', 'has_hostel' => false],
            ['name' => 'CENRO Oroquieta', 'has_hostel' => false],
            ['name' => 'PENRO Misamis Oriental', 'has_hostel' => false],
            ['name' => 'CENRO Initao', 'hostel_name' => 'Initao-Libertad PLS hostel', 'has_hostel' => true],
            ['name' => 'CENRO Gingoog', 'has_hostel' => false],
            ['name' => 'PENRO Camiguin', 'hostel_name' => 'Camiguin Hostel', 'has_hostel' => true],
            ['name' => 'PENRO Lanao del Norte', 'has_hostel' => false],
            ['name' => 'CENRO Iligan', 'has_hostel' => false],
            ['name' => 'CENRO Kalambugan', 'has_hostel' => false],

            // Region 11
            ['name' => 'Region 11', 'has_hostel' => false],
            ['name' => 'PENRO Davao Oriental', 'has_hostel' => false],
            ['name' => 'CENRO Mati', 'has_hostel' => false],
            ['name' => 'CENRO Baganga', 'has_hostel' => false],
            ['name' => 'CENRO Manay', 'has_hostel' => false],
            ['name' => 'CENRO Lupon', 'has_hostel' => false],
            ['name' => 'PENRO Davao del Norte', 'has_hostel' => false],
            ['name' => 'CENRO New Corella', 'has_hostel' => false],
            ['name' => 'CENRO Panabo', 'has_hostel' => false],
            ['name' => 'PENRO Davao de Oro', 'has_hostel' => false],
            ['name' => 'CENRO Monkayo', 'has_hostel' => false],
            ['name' => 'CENRO Maco', 'has_hostel' => false],
            ['name' => 'PENRO Davao del Sur', 'has_hostel' => false],
            ['name' => 'CENRO Digos', 'has_hostel' => false],
            ['name' => 'CENRO Malalag', 'has_hostel' => false],
            ['name' => 'CENRO Davao City', 'has_hostel' => false],
            ['name' => 'PENRO Davao Occidental', 'has_hostel' => false],

            // Region 12
            ['name' => 'Region 12', 'has_hostel' => false],
            ['name' => 'PENRO Cotabato', 'has_hostel' => false],
            ['name' => 'CENRO Midsayap', 'has_hostel' => false],
            ['name' => 'CENRO Matalam', 'has_hostel' => false],
            ['name' => 'PENRO Sultan Kudarat', 'has_hostel' => false],
            ['name' => 'CENRO Tacurong City', 'has_hostel' => false],
            ['name' => 'CENRO Kalamansig', 'has_hostel' => false],
            ['name' => 'PENRO South Cotabato', 'has_hostel' => false],
            ['name' => 'CENRO Banoa', 'has_hostel' => false],
            ['name' => 'CENRO General Santos City', 'has_hostel' => false],
            ['name' => 'PENRO Sarangani', 'has_hostel' => false],
            ['name' => 'CENRO Kiamba', 'has_hostel' => false],
            ['name' => 'CENRO Glan', 'has_hostel' => false],

            // Region 13 (Caraga)
            ['name' => 'Region 13', 'has_hostel' => false],
            ['name' => 'PENRO Agusan del Norte', 'has_hostel' => false],
            ['name' => 'CENRO Nasipit', 'has_hostel' => false],
            ['name' => 'CENRO Tubay', 'has_hostel' => false],
            ['name' => 'PENRO Agusan del Sur', 'has_hostel' => false],
            ['name' => 'CENRO Bayugan', 'has_hostel' => false],
            ['name' => 'CENRO Loreto', 'has_hostel' => false],
            ['name' => 'CENRO Bunawan', 'has_hostel' => false],
            ['name' => 'CENRO Talacogon', 'has_hostel' => false],
            ['name' => 'PENRO Surigao del Norte', 'has_hostel' => false],
            ['name' => 'CENRO Tubod', 'has_hostel' => false],
            ['name' => 'PENRO Surigao del Sur', 'has_hostel' => false],
            ['name' => 'CENRO Bislig City', 'has_hostel' => false],
            ['name' => 'CENRO Cantilan', 'has_hostel' => false],
            ['name' => 'CENRO Lianga', 'has_hostel' => false],
            ['name' => 'PENRO Province of Dinagat Islands', 'has_hostel' => false],
        ];

        foreach ($offices as $office) {
            Office::create([
                'name' => $office['name'],
                'hostel_name' => $office['hostel_name'] ?? null,
                'has_hostel' => $office['has_hostel'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);
        }
    }
}
