<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Office;
use Carbon\Carbon;

class OfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $offices = [
            // NCR (National Capital Region)
            ['name' => 'Central Office'],
            ['name' => 'NCR'],
            ['name' => 'MEO North'],
            ['name' => 'MEO East'],
            ['name' => 'MEO West'],
            ['name' => 'MEO South'],

            // CAR (Cordillera Administrative Region)
            ['name' => 'CAR'],
            ['name' => 'PENRO Abra'],
            ['name' => 'CENRO Bangued'],
            ['name' => 'CENRO Lagangilang'],
            ['name' => 'PENRO Apayao'],
            ['name' => 'CENRO Calanasan'],
            ['name' => 'CENRO Conner'],
            ['name' => 'PENRO Benguet'],
            ['name' => 'CENRO Baguio'],
            ['name' => 'CENRO Baguias'],
            ['name' => 'PENRO Ifugao'],
            ['name' => 'CENRO Alfonso Lista'],
            ['name' => 'CENRO Lamut'],
            ['name' => 'PENRO Kalinga'],
            ['name' => 'CENRO Pinukpuk'],
            ['name' => 'CENRO Tabuk'],
            ['name' => 'PENRO Mt. Province'],
            ['name' => 'CENRO Paracelis'],
            ['name' => 'CENRO Sabangan'],

            // Region 1
            ['name' => 'Regional Office 1'],
            ['name' => 'PENRO Ilocos Norte'],
            ['name' => 'CENRO Laoag'],
            ['name' => 'CENRO Bangui'],
            ['name' => 'PENRO Ilocos Sur'],
            ['name' => 'CENRO Bantay'],
            ['name' => 'CENRO Tagudin'],
            ['name' => 'PENRO La Union'],
            ['name' => 'PENRO Pangasinan'],
            ['name' => 'CENRO Dagupan'],
            ['name' => 'CENRO Urdaneta'],
            ['name' => 'CENRO Alaminos'],

            // Region 2
            ['name' => 'Regional Office 2'],
            ['name' => 'PENRO Batanes'],
            ['name' => 'PENRO Cagayan'],
            ['name' => 'CENRO Alcala'],
            ['name' => 'CENRO Solana'],
            ['name' => 'CENRO Aparri'],
            ['name' => 'CENRO Sanchez Mira'],
            ['name' => 'PENRO Isabela'],
            ['name' => 'CENRO Cabagan'],
            ['name' => 'CENRO Palanan'],
            ['name' => 'CENRO Cauayan'],
            ['name' => 'CENRO Naguilian'],
            ['name' => 'CENRO San Isidro'],
            ['name' => 'PENRO Nueva Vizcaya'],
            ['name' => 'CENRO Aritao'],
            ['name' => 'CENRO Dupax'],
            ['name' => 'PENRO Quirino'],
            ['name' => 'CENRO Diffun'],
            ['name' => 'CENRO Nagtipunan'],

            // Region 3
            ['name' => 'Regional Office 3'],
            ['name' => 'PENRO Aurora'],
            ['name' => 'CENRO Casiguran'],
            ['name' => 'CENRO Dingalan'],
            ['name' => 'PENRO Bataan'],
            ['name' => 'CENRO Bagac'],
            ['name' => 'CENRO Dinalupihan'],
            ['name' => 'PENRO Bulacan'],
            ['name' => 'CENRO Baliuag'],
            ['name' => 'CENRO Guiguinto'],
            ['name' => 'PENRO Nueva Ecija'],
            ['name' => 'CENRO Cabanatuan City'],
            ['name' => 'CENRO Muñoz'],
            ['name' => 'PENRO Pampanga'],
            ['name' => 'PENRO Tarcal'],
            ['name' => 'CENRO Camiling'],
            ['name' => 'CENRO Capas'],
            ['name' => 'PENRO Zamales'],
            ['name' => 'CENRO Masinloc'],
            ['name' => 'CENRO Olangapo City'],

            // region 4a
            ['name' => 'CALABARZON'],
            ['name' => 'PENRO Cavite'],
            ['name' => 'PENRO Laguna'],
            ['name' => 'CENRO Sta. Cruz'],
            ['name' => 'PENRO Batangas'],
            ['name' => 'CENRO Lipa City'],
            ['name' => 'CENRO Calaca'],
            ['name' => 'PENRO Rizal'],
            ['name' => 'PENRO Quezon'],
            ['name' => 'CENRO Calauag'],
            ['name' => 'CENRO Catanauan'],
            ['name' => 'CENRO Tayabas'],
            ['name' => 'CENRO Real'],

            // region 4b
            ['name' => 'MIMAROPA'],
            ['name' => 'PENRO Occidental Mindoro'],
            ['name' => 'CENRO Sablayan'],
            ['name' => 'CENRO San Jose'],
            ['name' => 'PENRO Oriental Mindoro'],
            ['name' => 'CENRO Roxas'],
            ['name' => 'PENRO Marinduque'],
            ['name' => 'PENRO Palawan'],
            ['name' => 'CENRO Brooke\'s Point'],
            ['name' => 'CENRO Coron'],
            ['name' => 'CENRO Puerto Princesa'],
            ['name' => 'CENRO Quezon'],
            ['name' => 'CENRO Roxas'],
            ['name' => 'CENRO Taytay'],

            // Region 5
            ['name' => 'Regional Office 5'],
            ['name' => 'PENRO Albay'],
            ['name' => 'CENRO Guinobatan'],
            ['name' => 'PENRO Camarines Norte'],
            ['name' => 'PENRO Camarines Sur'],
            ['name' => 'CENRO Iriga City'],
            ['name' => 'CENRO Goa'],
            ['name' => 'CENRO Sipocot'],
            ['name' => 'CENRO Mobo'],
            ['name' => 'CENRO San Jacinto'],
            ['name' => 'PENRO Catanduanes'],
            ['name' => 'PENRO Masbate'],
            ['name' => 'PENRO Sorsogon'],

            // Region 6
            ['name' => 'Regional Office 6'],
            ['name' => 'PENRO Aklan'],
            ['name' => 'CENRO Boracay'],
            ['name' => 'PENRO Ilo-Ilo'],
            ['name' => 'CENRO Guimbal'],
            ['name' => 'CENRO Barotac Nuevo'],
            ['name' => 'CENRO Sara'],
            ['name' => 'PENRO Antique'],
            ['name' => 'CENRO Belision'],
            ['name' => 'CENRO Culasi'],
            ['name' => 'PENRO Guimaras'],
            ['name' => 'PENRO Negros Occidental'],
            ['name' => 'CENRO Bago City'],
            ['name' => 'CENRO Cadiz City'],
            ['name' => 'CENRO Kabankalan City'],
            ['name' => 'PENRO Capiz'],
            ['name' => 'CENRO Mambusao'],

            // Region 7
            ['name' => 'Regional Office 7'],
            ['name' => 'PENRO Cebu'],
            ['name' => 'CENRO Cebu City'],
            ['name' => 'CENRO Argao'],
            ['name' => 'PENRO Bohol'],
            ['name' => 'CENRO Tagbilaran City'],
            ['name' => 'CENRO Talibon'],
            ['name' => 'PENRO Negros Oriental'],
            ['name' => 'CENRO Dumaguete City'],
            ['name' => 'CENRO Ayungon'],
            ['name' => 'CENRO Siquijor'],

            // Region 8
            ['name' => 'Regional Office 8'],
            ['name' => 'PENRO Leyte'],
            ['name' => 'CENRO Palo'],
            ['name' => 'CENRO Baybay'],
            ['name' => 'CENRO Ormoc'],
            ['name' => 'PENRO Southern Leyte'],
            ['name' => 'CENRO Maasin'],
            ['name' => 'CENRO San Juan'],
            ['name' => 'PENRO Samar'],
            ['name' => 'CENRO Centro Catbalogan'],
            ['name' => 'CENRO Sta. Rita'],
            ['name' => 'PENRO Eastern Samar'],
            ['name' => 'CENRO Borongan'],
            ['name' => 'CENRO Dolores'],
            ['name' => 'PENRO Northern Samar'],
            ['name' => 'CENRO Catarman'],
            ['name' => 'CENRO Pambujan'],
            ['name' => 'PENRO Biliran'],

            // Region 9
            ['name' => 'Regional Office 9'],
            ['name' => 'PENRO Zamboanga del Sur'],
            ['name' => 'CENRO Guipos'],
            ['name' => 'CENRO Ramon Magsaysay'],
            ['name' => 'PENRO Zamboanga del Norte'],
            ['name' => 'CENRO Piñan'],
            ['name' => 'CENRO Liloy'],
            ['name' => 'CENRO Manukan'],
            ['name' => 'CENRO Siocon'],
            ['name' => 'PENRO Zamboanga Sibugay'],
            ['name' => 'CENRO Imelda'],
            ['name' => 'CENRO Kabasalan'],
            ['name' => 'CENRO Zamboanga City'],

            // Region 10
            ['name' => 'Regional Office 10'],
            ['name' => 'PENRO Bukidnon'],
            ['name' => 'CENRO Manolo Fortich'],
            ['name' => 'CENRO Valencia'],
            ['name' => 'CENRO Don Carlos'],
            ['name' => 'CENRO Talakag'],
            ['name' => 'PENRO Misamis Occidental'],
            ['name' => 'CENRO Ozamis'],
            ['name' => 'CENRO Oroquieta'],
            ['name' => 'PENRO Misamis Oriental'],
            ['name' => 'CENRO Initao'],
            ['name' => 'CENRO Gingoog'],
            ['name' => 'PENRO Camiguin'],
            ['name' => 'PENRO Lanao del Norte'],
            ['name' => 'CENRO Iligan'],
            ['name' => 'CENRO Kalambugan'],

            // Region 11
            ['name' => 'Regional Office 11'],
            ['name' => 'PENRO Davao Oriental'],
            ['name' => 'CENRO Mati'],
            ['name' => 'CENRO Baganga'],
            ['name' => 'CENRO Manay'],
            ['name' => 'CENRO Lupon'],
            ['name' => 'PENRO Davao del Norte'],
            ['name' => 'CENRO New Corella'],
            ['name' => 'CENRO Panabo'],
            ['name' => 'PENRO Davao de Oro'],
            ['name' => 'CENRO Monkayo'],
            ['name' => 'CENRO Maco'],
            ['name' => 'PENRO Davao del Sur'],
            ['name' => 'CENRO Digos'],
            ['name' => 'CENRO Malalag'],
            ['name' => 'CENRO Davao City'],
            ['name' => 'PENRO Davao Occidental'],

            // Region 12
            ['name' => 'Regional Office 12'],
            ['name' => 'PENRO Cotabato'],
            ['name' => 'CENRO Midsayap'],
            ['name' => 'CENRO Matalam'],
            ['name' => 'PENRO Sultan Kudarat'],
            ['name' => 'CENRO Tacurong City'],
            ['name' => 'CENRO Kalamansig'],
            ['name' => 'PENRO South Cotabato'],
            ['name' => 'CENRO Banoa'],
            ['name' => 'CENRO General Santos City'],
            ['name' => 'PENRO Sarangani'],
            ['name' => 'CENRO Kiamba'],
            ['name' => 'CENRO Glan'],

            // Region 13 (Caraga)
            ['name' => 'Regional Office 13'],
            ['name' => 'PENRO Agusan del Norte'],
            ['name' => 'CENRO Nasipit'],
            ['name' => 'CENRO Tubay'],
            ['name' => 'PENRO Agusan del Sur'],
            ['name' => 'CENRO Bayugan'],
            ['name' => 'CENRO Loreto'],
            ['name' => 'CENRO Bunawan'],
            ['name' => 'CENRO Talacogon'],
            ['name' => 'PENRO Surigao del Norte'],
            ['name' => 'CENRO Tubod'],
            ['name' => 'PENRO Surigao del Sur'],
            ['name' => 'CENRO Bislig City'],
            ['name' => 'CENRO Cantilan'],
            ['name' => 'CENRO Lianga'],
            ['name' => 'PENRO Province of Dinagat Islands'],
        ];

        foreach ($offices as $office) {
            Office::create([
                'name' => $office['name'],
                'has_hostel' => $office['has_hostel'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);
        }
    }
}
